site_name: acme-engine
site_description: Compute and Orchestration Engine
site_url: https://blackwhitehere.github.io/acme-engine
repo_url: https://github.com/blackwhitehere/acme-engine
repo_name: blackwhitehere/acme-engine
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.action.edit

nav:
  - Overview: index.md
  - User:
    - Installation: user/install.md
    - Getting Started: user/getting-started.md
    - User Guides: user/user-guides.md
    - Features: user/features.md
    - Cheat Sheet: user/cheat-sheet.md
    - Release Notes: user/release-notes.md
  - Developer:
    - Architecture: developer/architecture.md
    - API Reference: developer/api-reference.md
    - Contributing: developer/contributing.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocstrings

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/blackwhitehere/acme-engine

extra_css:
  - stylesheets/extra.css