name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps`.
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          pipx install uv

      - name: Sync dependencies (dev)
        run: |
          uv sync --dev

      - name: Cache mkdocs site build (optional)
        if: hashFiles('docs/mkdocs.yml') != ''
        uses: actions/cache@v4
        with:
          path: .cache
          key: mkdocs-${{ runner.os }}-${{ hashFiles('docs/mkdocs.yml') }}

      - name: Validate tooling
        run: |
          ./.venv/bin/python -V || true
          ./.venv/bin/ruff -V || true
          ./.venv/bin/pytest -q -k "-e slow" || true
          ./.venv/bin/mkdocs --version || true
